MDScreen:
    MDToolbar:
        id: toolbar
        title: "Swipe"
        elevation: 10
        pos_hint: {"top": 1}
    MDSwiper:
        id: myswiper
        size_hint_y: None
        height: root.height - toolbar.height - dp(40)
        y: root.height - self.height - toolbar.height - dp(20)
        #MDSwiperItem:
        #    FitImage:
        #        source: "samsung_tab_1-500x500.jpg"
        #        radius: [20,]
